services:
    client:
        build:
            context: ./client/
            dockerfile: Dockerfile.nginx
        ports:
            - '8077:8077' # nginx static
        depends_on:
            - server
        networks:
            - 'kr-network'

    server:
        build:
            context: ./server/
            dockerfile: Dockerfile.server
        ports:
            - '8005:8005'
            - '8011:8011'
        networks:
            - 'kr-network'
networks:
    kr-network:
        driver: bridge
