# Используем официальный образ Node.js
FROM node:20-alpine

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем зависимости
COPY package.json yarn.lock ./

# Устанавливаем зависимости через yarn
RUN yarn install --frozen-lockfile

# Копируем остальной исходный код
COPY . .

# Указываем порт, который будет слушать WebSocket-сервер
EXPOSE 8005 8010

# Команда запуска сервера
CMD ["yarn", "start"]
